### ISSUE TITLE
sw spi speed on orange pi zero

### ISSUE THREAD

**Issue by ifengchao** [wuhanstudio/u8g2-arm-linux#6]
Hi WuHan, thanks for your great work, it's working with my orange pi zero, but when i try to show some animation pics, it's about one second delay between two frames. I wonder how it works on your pi zero?

Here's my sw spi gpio config:

#define OLED_SPI_PIN_MOSI           0
#define OLED_SPI_PIN_SCK            3

// Use a different pin here rather than default SPI pins, which may cause issue
#define OLED_SPI_PIN_RES            2
#define OLED_SPI_PIN_DC             10
#define OLED_SPI_PIN_CS             13

and the code showing images one after another:
         u8g2_DrawXBM(&u8g2, 0, 0, 128, 64, col1);
         u8g2_SendBuffer(&u8g2);
//no delay here.
         u8g2_DrawXBM(&u8g2, 0, 0, 128, 64, col2);
         u8g2_SendBuffer(&u8g2);
....

And i've tried change the spi speed from 500KHZ to 1MHZ, but it doesn't help.

**Comment by wuhanstudio** [comment]
Hi, 

If you'd like to increase the speed, you may be interested with my discussion with sgjava here where he increases the speed by replacing sysfs with chardev:

https://github.com/olikraus/u8g2/pull/1650#issuecomment-961049362

And here's his port:

https://github.com/sgjava/u8g2/tree/master/sys/arm-linux

**Comment by ifengchao** [comment]
> Hi,
> 
> If you'd like to increase the speed, you may be interested with my discussion with sgjava here where he increases the speed by replacing sysfs with chardev:
> 
> [olikraus/u8g2#1650 (comment)](https://github.com/olikraus/u8g2/pull/1650#issuecomment-961049362)
> 
> And here's his port:
> 
> https://github.com/sgjava/u8g2/tree/master/sys/arm-linux

OK, appreciate for the info, i'll try that and post the result here. :)

**Comment by ifengchao** [comment]
Thanks Wuhan, it's worked with impressive fast hw spi speed !!!
Simply pulled sgjava's post and changed two pins.
