### ISSUE TITLE
Cannot compile examples - missing files

### ISSUE THREAD

**Issue by karlo922** [wuhanstudio/u8g2-arm-linux#9]
With your current content of the lib, I could not compile any of the examples:
``` :~/test/u8g2-arm-linux/examples/c-examples/u8g2_4wire_sw_spi $ make CPPFLAGS=-DPERIPHERY_GPIO_CDEV_SUPPORT=1 CC=gcc CXX=g++
gcc -I ../../../drivers -I ../../../csrc -I ../../../port -W -Wall -D __ARM_LINUX__ -DPERIPHERY_GPIO_CDEV_SUPPORT=1  -c -o u8g2_4wire_sw_spi.o u8g2_4wire_sw_spi.c
In file included from u8g2_4wire_sw_spi.c:1:
../../../port/u8g2port.h:9:10: fatal error: gpio.h: No such file or directory
    9 | #include "gpio.h"
      |          ^~~~~~~~
compilation terminated.
make: *** [<builtin>: u8g2_4wire_sw_spi.o] Error 1
```

The directory ```c-periphery``` is empty. When I copied the correct files in it, it worked again

**Comment by wuhanstudio** [comment]
Hi,

The c-periphery is a git submodule, which can be initialised using:

> git submodule init
> git submodule update

**Comment by karlo922** [comment]
Thanks! Maybe you could add this in your readme for others like me ;)

**Comment by karlo922** [comment]
Saw that you already have mentionned that a ```git clone``` alone is not enough. Closing the issue

**Comment by wuhanstudio** [comment]
Yes, another alternative is to use `git clone —recursive` to recursively initialise submodules while cloning.
